# Generated by Django 3.2.19 on 2023-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230531_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='domain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
